spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/expenseguard_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.expenseguard: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
