spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/expenseguard_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    com.expenseguard: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
